### ISSUE TITLE
Save tag and not field

### ISSUE THREAD

**Issue by nodiaque** [loganmarchione/docker-speedtest-influxdbv2#27]
Hello,

I see that some data are saved as field instead of tag. In fact, everything that is speedtest_server_* (speedtest_server_name, etc). Is it possible to convert this in tag?

Problem is since it's by field, you cannot use them in group by, which prevent some type of graphic in grafana.

THank you

**Comment by loganmarchione** [comment]
Telegraf now has an official[ Internet Speed Monitor plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internet_speed). I recommend using that instead.

This project is being archived and the container image will be removed from Docker Hub. You can still build the container image from source if you'd like.
