### ISSUE TITLE
ModuleNotFoundError: No module named 'influxdb_client'

### ISSUE THREAD

**Issue by andywitt1** [loganmarchione/docker-speedtest-influxdbv2#39]
I am trying to run this docker container on my TrueNas to monitor internet speed. I have made a custom-application. Whenever I run it, I get the following error: 

2023-11-21 23:32:41.227283+00:00Traceback (most recent call last):
2023-11-21 23:32:41.227317+00:00File "./speedtest.py", line 10, in <module>
2023-11-21 23:32:41.227323+00:00from influxdb_client import InfluxDBClient
2023-11-21 23:32:41.227326+00:00ModuleNotFoundError: No module named 'influxdb_client'

My thought is that influxdb_client would be inherent to the docker container so I don't know why I'm getting the error.

**Comment by loganmarchione** [comment]
I plan on deprecating this container soon, so I would advise you to use the official telegraf input plugin.

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internet_speed

However, you are correct in that the client should be built into the docker container. Is your TrueNAS instance  based on TrueNAS Core (FreeBSD) or TrueNAS Scale (Linux)?

**Comment by loganmarchione** [comment]
Telegraf now has an official[ Internet Speed Monitor plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internet_speed). I recommend using that instead.

This project is being archived and the container image will be removed from Docker Hub. You can still build the container image from source if you'd like.
