### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by shad-lp** [loganmarchione/docker-speedtest-influxdbv2#6]
@loganmarchione 

Hello, thanks for your image.
I'm facing issues with an error about too many requests :

```
#####
Script starting!
#####
STATE: Starting at 2021-09-01T11:01:04.207437
STATE: Sleep time between runs set to 3600 seconds
STATE: Checking environment variables...
STATE: Connecting to InfluxDB...
STATE: Running database check
STATE: Connection pass
STATE: Loop running at 2021-09-01T11:01:04.219056
STATE: Speedtest running
[2021-09-01 11:01:04.479] [error] Limit reached:

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>

Traceback (most recent call last):
  File "./speedtest.py", line 122, in <module>
    speedtest()
  File "./speedtest.py", line 46, in speedtest
    my_speed = subprocess.run(['/usr/bin/speedtest', '--accept-license', '--accept-gdpr', '--format=json'], stdout=subprocess.PIPE, text=True, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/speedtest', '--accept-license', '--accept-gdpr', '--format=json']' returned non-zero exit status 173.
```

It never happened in many months of use. Is there any change to Ookla concerning request limit or restriction ? or something else done on your side ?

**Comment by loganmarchione** [comment]
I didn't change anything. Maybe Ookla changed their rate limit? How often were you running the script?

**Comment by shad-lp** [comment]
Every 3600s as you can see in the logs.
But the speedtest tries to run every minute if it fails.
I'll check if it manages to succeed (if it is really a rate limit, then it should make it soon).

EDIT : Last successful speedtest was 5 hours ago.

![image](https://user-images.githubusercontent.com/43928955/131680642-2dcb3a5f-af9f-4019-a2f3-406baa6431ae.png)

**Comment by shad-lp** [comment]
Back to normal, seems like a bug on Ookla's side.

**Comment by Gurkengewuerz** [comment]
Hey @shadowking001 do you want to share your dashboard json? :)

**Comment by shad-lp** [comment]
@Gurkengewuerz Hello, I don't know how to extract the sole speedtest part, so I'll share the entire dashboard, you will get off what you don't need. ;)

[https://pastebin.com/epzyr7dR](https://pastebin.com/epzyr7dR)

**Comment by Gurkengewuerz** [comment]
> @Gurkengewuerz Hello, I don't know how to extract the sole speedtest part, so I'll share the entire dashboard, you will get off what you don't need. ;)
> 
> [https://pastebin.com/epzyr7dR](https://pastebin.com/epzyr7dR)

Thanks ☺️🙌🏼
