### ISSUE TITLE
Feature Request: Write URL to influxdb

### ISSUE THREAD

**Issue by GazaShaggy** [loganmarchione/docker-speedtest-influxdbv2#7]
Working fine with influxdb V2.1.1 just wondering if you could also write the Speedtest URL to the database as well

**Comment by loganmarchione** [comment]
@GazaShaggy Thanks for the v2.1.1 confirmation. I used it to close #5.

For your issue, I just pushed a new tag. Can you test for the `result_url` field and confirm if working? I tested on a v1.8 and v2.0 database and it worked for me.
`docker pull loganmarchione/docker-speedtest-influxdbv2:1.0.1`

**Comment by GazaShaggy** [comment]
Yes cheers it saves in the database fine, the math's I'm doing in grafana is the number this outputs divided by 125000 is that correct (does bps = bits per second) cause grafana shows  7.01Mb/s if I set it to bits/sec(SI)


> STATE: RESULTS ARE SAVED IN BPS NOT MBPS
STATE: Your download      7015019 bps
STATE: Your upload        3974823 bps
STATE: Your ping latency  8.673 ms
STATE: Your ping jitter   2.828 ms
STATE: Your server info   48362 GSL Networks Adelaide Australia colocity.speedtest.gslnetworks.com
STATE: Your URL is        https://www.speedtest.net/result/c/d19f0fec-338b-45a8-b6e6-3bb0e7f2a0b8
speedtest,service=speedtest.net,host=Shaggys download=7015019,upload=3974823,ping_latency=8.673,ping_jitter=2.828,speedtest_server_id=48362,speedtest_server_name="GSL Networks",speedtest_server_location="Adelaide",speedtest_server_country="Australia",speedtest_server_host="colocity.speedtest.gslnetworks.com",result_url="https://www.speedtest.net/result/c/d19f0fec-338b-45a8-b6e6-3bb0e7f2a0b8"
STATE: Writing to database
STATE: Sleeping for 1800 seconds

**Comment by loganmarchione** [comment]
I'm reading the man page for the script and saw this (emphasis mine).

> The human-readable format defaults to Mbps and any machine-readable formats (csv, tsv, json, jsonl, json-pretty) use **bytes** as the unit of measure with max precision.

> The  bytes per second measurements can be transformed into the human-readable output format default unit of megabits (Mbps) by dividing the bytes per second value by 125,000.

So you are correct, it is bytes-per-second. I'll add a note about that.

**Comment by GazaShaggy** [comment]
Cheers I'll close the issue
